name = "drinks-api"
main = "src/index.ts"
compatibility_date = "2026-01-26"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 15, period = 60 }

[[d1_databases]]
binding = "DB"
database_name = "drinks-api-db"
database_id = "xxxx"

[observability]
enabled = true
head_sampling_rate = 0.05

[observability.logs]
enabled = true
head_sampling_rate = 0.05
invocation_logs = true
